// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Sl-JHe-HLFDi1ykcDBrRcqb2vmaVfVA',
    appId: '1:715073406643:web:3b8e1b4c9f881f3b6392c6',
    messagingSenderId: '715073406643',
    projectId: 'chat-app-d9e60',
    authDomain: 'chat-app-d9e60.firebaseapp.com',
    databaseURL: 'https://chat-app-d9e60-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-d9e60.appspot.com',
    measurementId: 'G-1898QXGHDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8SgUammBoCbXX5KrItVPNE8gv_TFQSwo',
    appId: '1:715073406643:android:c142cac762f3eed56392c6',
    messagingSenderId: '715073406643',
    projectId: 'chat-app-d9e60',
    databaseURL: 'https://chat-app-d9e60-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-d9e60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4vG6_PFRHtBlpTD_X0TTe_HMDmiQAO04',
    appId: '1:715073406643:ios:68c877d3621b05da6392c6',
    messagingSenderId: '715073406643',
    projectId: 'chat-app-d9e60',
    databaseURL: 'https://chat-app-d9e60-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-d9e60.appspot.com',
    iosClientId: '715073406643-s356cna4oeicpsv6q728vou1a0jbq1vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4vG6_PFRHtBlpTD_X0TTe_HMDmiQAO04',
    appId: '1:715073406643:ios:68c877d3621b05da6392c6',
    messagingSenderId: '715073406643',
    projectId: 'chat-app-d9e60',
    databaseURL: 'https://chat-app-d9e60-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-d9e60.appspot.com',
    iosClientId: '715073406643-s356cna4oeicpsv6q728vou1a0jbq1vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
